In [1]:
import numpy as np
from pandas import DataFrame,Series
import pandas as pd

In [2]:
r1= np.arange(5)
r1

array([0, 1, 2, 3, 4])

In [3]:
np.save('SingleA',r1)

In [14]:
r3=np.load('SingleA.npy')
r3

array([0, 1, 2, 3, 4])

In [6]:
r2=np.arange(10)
r2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.save('LongerA.npy',r2)

In [15]:
r4=np.load('LongerA.npy')
r4

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
np.savez('rboth', x=r3,y=r4)

In [21]:
myboth=np.load('rboth.npz')

In [23]:
myboth['x']

array([0, 1, 2, 3, 4])

In [24]:
r5= np.arange(10)
r5

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
r6=np.arange(15)
r6

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [31]:
np.savez('both1.npz',x=r5,y=r6)

In [32]:
both2 = np.load('both1.npz')

In [33]:
both2['x']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
both2['y']

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [36]:
r7= np.array([[2,3,6],[9,8,2]])
r7

array([[2, 3, 6],
       [9, 8, 2]])

In [39]:
np.savetxt('mytext.txt',r7,delimiter=',')

In [44]:
1

1

In [42]:
r9=np.loadtxt('mytext.txt',delimiter=',')

In [43]:
r9

array([[2., 3., 6.],
       [9., 8., 2.]])

In [48]:
r10=np.arange(50).reshape(5,10)
r10

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [49]:
np.savetxt('myt.txt',r10,delimiter='?')

In [51]:
myd=np.loadtxt('myt.txt',delimiter='?')

In [52]:
myd

array([[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.],
       [10., 11., 12., 13., 14., 15., 16., 17., 18., 19.],
       [20., 21., 22., 23., 24., 25., 26., 27., 28., 29.],
       [30., 31., 32., 33., 34., 35., 36., 37., 38., 39.],
       [40., 41., 42., 43., 44., 45., 46., 47., 48., 49.]])

In [53]:
my1=myd
my1

array([[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.],
       [10., 11., 12., 13., 14., 15., 16., 17., 18., 19.],
       [20., 21., 22., 23., 24., 25., 26., 27., 28., 29.],
       [30., 31., 32., 33., 34., 35., 36., 37., 38., 39.],
       [40., 41., 42., 43., 44., 45., 46., 47., 48., 49.]])

In [ ]:
m