In [1]:
import numpy as np
from pandas import Series,DataFrame
import pandas as pd

In [3]:
bl= np.random.permutation(4)
bl

array([2, 3, 0, 1])

In [5]:
b2=np.random.randint(0,4,size=8)
b2

array([3, 0, 3, 3, 3, 3, 1, 2])

In [7]:
box=[1,2,3,4]

In [10]:
b3=np.random.randint(0,len(box),size=8)
b3

array([3, 3, 1, 3, 1, 0, 0, 2])

In [12]:
d1=DataFrame(np.arange(4*4).reshape(4,4))
d1

0   1   2   3
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15

In [14]:
d1.take(bl)

0   1   2   3
2   8   9  10  11
3  12  13  14  15
0   0   1   2   3
1   4   5   6   7

use random.randint(beginning,numbers to be permutated,size=[size]
use np.dataframe.take(blender)

In [25]:
r1=np.array([3,4,5,6])
r1

array([3, 4, 5, 6])

In [26]:
r2=np.random.randint(0,len(r1),8)
r2

array([0, 1, 3, 1, 1, 3, 0, 0])

In [29]:
r3=r1.take(r2)
r3

array([3, 4, 6, 4, 4, 6, 3, 3])

In [28]:
r1.take(b3)

array([6, 6, 4, 6, 4, 3, 3, 5])